# Generated by Django 4.1.2 on 2022-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_api', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
